# Generated by Django 5.2.7 on 2025-11-21 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('governorate', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'medecin',
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id_RDV', models.AutoField(db_column='id_RDV', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_med', models.ForeignKey(db_column='id_med', on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='users.medecin')),
                ('id_patient', models.ForeignKey(db_column='id_patient', on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rdv',
            },
        ),
    ]
